# for local deployment

services:
  app:
    container_name: accounting-service-app
    build:
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=dev
        - INSTALL_DEBUG_TOOLS=true
        - APP_NAME=accounting-service
        - APP_VERSION=${APP_VERSION:-UNKNOWN}
        - COMMIT_SHA=${COMMIT_SHA:-UNKNOWN}
    ports:
    - "127.0.0.1:8900:8900"
    cap_add:
    - SYS_PTRACE
    environment:
    - APP_PORT=8900
    - APP_DEBUG=true
    - APP_RELOAD=true
    - LOGGING_LEVEL=DEBUG
    develop:
      watch:
      - action: sync
        path: ./app
        target: /code/app
      - action: rebuild
        path: pdm.lock
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: accounting-service-db
    environment:
      POSTGRES_USER: accounting_service
      POSTGRES_PASSWORD: accounting_service
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accounting_service"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 1s
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
