services:
  app:
    image: "accounting-service:${APP_VERSION}-${ENVIRONMENT}"
    build:
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT
        - APP_NAME
        - APP_VERSION
        - COMMIT_SHA
    ports:
    - "127.0.0.1:8100:8000"
    environment:
    - APP_DEBUG=true
    - AWS_ACCESS_KEY_ID=xxx
    - AWS_SECRET_ACCESS_KEY=xxx
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_MAX_ATTEMPTS=3
    - AWS_RETRY_MODE=standard
    develop:
      watch:
      - action: sync+restart
        path: ./app
        target: /code/app
      - action: rebuild
        path: pdm.lock
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_started

  migration:
    image: "accounting-service:${APP_VERSION}-${ENVIRONMENT}"
    command:
      - sh
      - -cx
      - |
        alembic upgrade head &&
        alembic revision --autogenerate
    volumes:
      - ./alembic/versions:/code/alembic/versions
    depends_on:
      db:
        condition: service_healthy

  test:
    image: "accounting-service:${APP_VERSION}-${ENVIRONMENT}"
    command:
    - sh
    - -cx
    - |
      alembic downgrade base &&
      alembic upgrade head &&
      python -m pytest -vv --cov=app tests &&
      python -m coverage xml &&
      python -m coverage html
    environment:
      - DB_HOST=db-test
    volumes:
      - ./tests:/code/tests
    depends_on:
      db-test:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: accounting_service
      POSTGRES_PASSWORD: accounting_service
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accounting_service"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 1s
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    extends: db
    restart: "no"
    ports: !override
      - "127.0.0.1:5434:5432"
    volumes: !reset []

  queue:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "127.0.0.1:9324:9324"
      - "127.0.0.1:9325:9325"
    volumes:
    - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  pgdata: {}
