# docker-compose.yml for local deployment

services:
  app:
    container_name: accounting-service
    build:
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:8900:8900"
    cap_add:
    - SYS_PTRACE
    environment:
    - APP_DEBUG=true
    - LOGGING_LEVEL=DEBUG
    - UVICORN_RELOAD=True
    develop:
      watch:
      - action: sync
        path: ./src/app
        target: /src/app
      - action: rebuild
        path: requirements.txt
      - action: rebuild
        path: docker-entrypoint.sh
