name: Build and publish the Docker image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      IMAGE_NAME: bluebrain/accounting-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          make build
        with:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
      - name: Publish To DockerHub
        run: |
          docker push ${{ env.IMAGE_NAME }}
